volumes:
  stored_data:
    name: stored_data
    external: true

services:
  postgres:
    image: pgvector/pgvector:pg16 
    container_name: pgvector_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marco -d sfaq_db"]
      interval: 30s       
      timeout: 5s          
      retries: 5          
      start_period: 15s   

  backend:
    build: ./backend
    container_name: semantic-faq-backend
    restart: always
    ports:
      - "8000:8000" 
    volumes:
      - stored_data:/backend_app/data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s      
      timeout: 5s          
      retries: 5          
      start_period: 40s
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: streamlit_faq
    restart: always
    ports:
      - "8501:8501" 
    depends_on:
      backend:
        condition: service_healthy