
services:
  postgres:
    image: pgvector/pgvector:pg16 
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_USER: marco
      POSTGRES_PASSWORD: marco
      POSTGRES_DB: sfaq_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: semantic-faq-backend
    restart: always
    ports:
      - "8000:8000" 

    volumes:
        - stored_data/data:/backend_app/data