name: semantic-faq-assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - fastapi
  - uvicorn
  - sqlalchemy
  - python-dotenv
  - pydantic
  - psycopg
  - pip
  - pip:
    - langchain-openai
    - langchain-core
    - openai
    - pgvector
    - .